on:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/*.overlay"
      - "config/*.conf"
  pull_request:
  workflow_dispatch:
name: Build firmware

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
